version: "3.8"

services:

  cli-test:
    build:
      context: .
      dockerfile: cli-test.Dockerfile
    tty: true
    stdin_open: true
    volumes:
    - /mnt/pi/work:/home/ffettes/work

  # cli:
  #   build:
  #     context: .
  #     dockerfile: cli.Dockerfile
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #   - /mnt/pi/work:/home/ffettes/work

  # cli-raw:
  #   build:
  #     context: .
  #     dockerfile: cli-raw.Dockerfile
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #   - /mnt/pi/work:/home/ffettes/work
  #   # - type: volume
  #   #   source: nfs-vol
  #   #   target: /home/ffettes/

# volumes:
#   nfs-vol:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "nfsvers=4,addr=${PI_IP},rw,async"
#       device: ":/nfsshare"
