version: '3'
services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "/home/ffettes/privtext/docker/appdata/firefox:/config:rw"
    shm_size: '2gb'
    environment:
      - X11VNC_EXTRA_OPTS=-skip_lockkeys -repeat
